// src/constants/icons/platformIcons.ts

import { CompactIconDef, IconCategory } from "./types";

const SOCIAL: Record<string, CompactIconDef> = {
  facebook: ["FA5", "facebook", "#1877F2", "social", ["facebook", "social", "meta"]],
  instagram: ["FA5", "instagram", "#E4405F", "social", ["instagram", "social", "photo", "meta"]],
  twitter: ["FA5", "twitter", "#1DA1F2", "social", ["twitter", "x", "social", "tweet"]],
  x: ["Ion", "logo-x", "#000000", "social", ["x", "twitter", "social", "tweet"]],
  linkedin: ["FA5", "linkedin", "#0A66C2", "social", ["linkedin", "professional", "jobs"]],
  snapchat: ["FA5", "snapchat", "#FFFC00", "social", ["snapchat", "social", "photo"]],
  pinterest: ["FA5", "pinterest", "#E60023", "social", ["pinterest", "social", "images"]],
  reddit: ["FA5", "reddit", "#FF4500", "social", ["reddit", "social", "forum"]],
  tiktok: ["MCI", "music-note", "#000000", "social", ["tiktok", "video", "social"]],
  threads: ["MCI", "at", "#000000", "social", ["threads", "social", "meta"]],
  mastodon: ["MCI", "elephant", "#6364FF", "social", ["mastodon", "social", "fediverse"]],
};

const COMMUNICATION: Record<string, CompactIconDef> = {
  whatsapp: [
    "FA5",
    "whatsapp",
    "#25D366",
    "communication",
    ["whatsapp", "chat", "messaging", "meta"],
  ],
  discord: [
    "FA5",
    "discord",
    "#5865F2",
    "communication",
    ["discord", "chat", "gaming", "community"],
  ],
  telegram: ["FA5", "telegram", "#0088CC", "communication", ["telegram", "chat", "messaging"]],
  slack: ["FA5", "slack", "#4A154B", "communication", ["slack", "work", "team", "chat"]],
  zoom: ["MCI", "video", "#2D8CFF", "communication", ["zoom", "video", "meeting", "call"]],
  skype: ["FA5", "skype", "#00AFF0", "communication", ["skype", "video", "call", "microsoft"]],
  teams: [
    "MCI",
    "microsoft-teams",
    "#6264A7",
    "communication",
    ["teams", "microsoft", "work", "meeting"],
  ],
  signal: [
    "MCI",
    "message-lock",
    "#3A76F0",
    "communication",
    ["signal", "chat", "secure", "messaging"],
  ],
  messenger: [
    "MCI",
    "facebook-messenger",
    "#0084FF",
    "communication",
    ["messenger", "facebook", "chat", "meta"],
  ],
  wechat: ["FA5", "weixin", "#09B83E", "communication", ["wechat", "weixin", "chat", "messaging"]],
  hellotalk: [
    "MCI",
    "chat-processing",
    "#0099FF",
    "communication",
    ["hellotalk", "language", "learning", "chat"],
  ],
};

const AI: Record<string, CompactIconDef> = {
  chatgpt: [
    "MCI",
    "robot-outline",
    "#10A37F",
    "ai",
    ["chatgpt", "openai", "ai", "gpt", "assistant"],
  ],
  openai: ["MCI", "robot", "#412991", "ai", ["openai", "chatgpt", "ai", "gpt"]],
  claude: [
    "MCI",
    "head-snowflake-outline",
    "#D97757",
    "ai",
    ["claude", "anthropic", "ai", "assistant"],
  ],
  anthropic: ["MCI", "head-snowflake", "#D97757", "ai", ["anthropic", "claude", "ai"]],
  perplexity: ["Ent", "network", "#20808D", "ai", ["perplexity", "ai", "search", "assistant"]],
  deepseek: ["MCI", "shark", "#4D6BFE", "ai", ["deepseek", "ai", "llm", "assistant"]],
  gemini: ["MCI", "creation", "#8E75B2", "ai", ["gemini", "google", "ai", "bard"]],
  bard: ["MCI", "creation", "#8E75B2", "ai", ["bard", "google", "ai", "gemini"]],
  copilot: ["MCI", "microsoft", "#0078D4", "ai", ["copilot", "microsoft", "ai", "github"]],
  midjourney: ["MCI", "image-filter-hdr", "#000000", "ai", ["midjourney", "ai", "image", "art"]],
  stablediffusion: ["MCI", "image-multiple", "#A855F7", "ai", ["stable diffusion", "ai", "image"]],
};

const DEVELOPER: Record<string, CompactIconDef> = {
  github: ["FA5", "github", "#181717", "developer", ["github", "git", "code", "developer"]],
  gitlab: ["FA5", "gitlab", "#FC6D26", "developer", ["gitlab", "git", "code", "developer"]],
  bitbucket: [
    "FA5",
    "bitbucket",
    "#0052CC",
    "developer",
    ["bitbucket", "git", "code", "developer"],
  ],
  stackoverflow: [
    "FA5",
    "stack-overflow",
    "#F58025",
    "developer",
    ["stackoverflow", "developer", "code", "questions"],
  ],
  leetcode: [
    "MCI",
    "code-braces",
    "#FFA116",
    "developer",
    ["leetcode", "coding", "interview", "algorithm"],
  ],
  codechef: [
    "MCI",
    "chef-hat",
    "#5B4638",
    "developer",
    ["codechef", "coding", "competitive", "programming"],
  ],
  geeksforgeeks: [
    "FA5",
    "code",
    "#2F8D46",
    "developer",
    ["geeksforgeeks", "gfg", "coding", "tutorial", "dsa"],
  ],
  hackerrank: [
    "MCI",
    "code-greater-than",
    "#00EA64",
    "developer",
    ["hackerrank", "coding", "interview"],
  ],
  codeforces: [
    "MCI",
    "code-brackets",
    "#1F8ACB",
    "developer",
    ["codeforces", "competitive", "programming"],
  ],
  npm: ["FA5", "npm", "#CB3837", "developer", ["npm", "node", "package", "developer"]],
  docker: ["MCI", "docker", "#2496ED", "developer", ["docker", "container", "developer"]],
  vercel: [
    "MCI",
    "triangle",
    "#000000",
    "developer",
    ["vercel", "hosting", "deployment", "nextjs"],
  ],
  netlify: ["MCI", "web", "#00C7B7", "developer", ["netlify", "hosting", "deployment", "web"]],
  render: ["MCI", "server", "#46E3B7", "developer", ["render", "hosting", "deployment", "cloud"]],
  railway: ["MCI", "train", "#0B0D0E", "developer", ["railway", "hosting", "deployment"]],
  heroku: ["MCI", "cloud", "#430098", "developer", ["heroku", "hosting", "deployment", "cloud"]],
  aws: ["FA5", "aws", "#FF9900", "developer", ["aws", "amazon", "cloud", "developer", "hosting"]],
  azure: ["MCI", "microsoft-azure", "#0078D4", "developer", ["azure", "microsoft", "cloud"]],
  gcp: ["MCI", "google-cloud", "#4285F4", "developer", ["gcp", "google", "cloud"]],
  digitalocean: [
    "MCI",
    "digital-ocean",
    "#0080FF",
    "developer",
    ["digitalocean", "cloud", "hosting"],
  ],
  cloudinary: [
    "MCI",
    "cloud-upload",
    "#3448C5",
    "developer",
    ["cloudinary", "cloud", "images", "media"],
  ],
  neondb: [
    "MCI",
    "flash",
    "#00E599",
    "developer",
    ["neondb", "neon", "database", "postgres", "serverless"],
  ],
  neon: [
    "MCI",
    "flash",
    "#00E599",
    "developer",
    ["neon", "neondb", "database", "postgres", "serverless"],
  ],
  supabase: ["MCI", "database", "#3ECF8E", "developer", ["supabase", "database", "backend"]],
  firebase: ["MCI", "firebase", "#FFCA28", "developer", ["firebase", "google", "backend"]],
  mongodb: ["MCI", "leaf", "#47A248", "developer", ["mongodb", "database", "nosql"]],
  planetscale: [
    "MCI",
    "database-outline",
    "#000000",
    "developer",
    ["planetscale", "database", "mysql"],
  ],
  replit: ["MCI", "code-tags", "#F26207", "developer", ["replit", "ide", "coding"]],
  codepen: ["FA5", "codepen", "#000000", "developer", ["codepen", "frontend", "code"]],
  codesandbox: ["MCI", "cube-outline", "#151515", "developer", ["codesandbox", "ide", "sandbox"]],
  figma: ["FA5", "figma", "#F24E1E", "developer", ["figma", "design", "ui", "ux"]],
  postman: ["MCI", "api", "#FF6C37", "developer", ["postman", "api", "testing"]],
};

const PRODUCTIVITY: Record<string, CompactIconDef> = {
  google: ["FA5", "google", "#4285F4", "productivity", ["google", "search", "account"]],
  gmail: ["MCI", "gmail", "#EA4335", "productivity", ["gmail", "email", "google", "mail"]],
  outlook: [
    "MCI",
    "microsoft-outlook",
    "#0078D4",
    "productivity",
    ["outlook", "email", "microsoft", "mail"],
  ],
  yahoo: ["FA5", "yahoo", "#6001D2", "productivity", ["yahoo", "email", "mail"]],
  protonmail: [
    "MCI",
    "email-lock",
    "#8B89CC",
    "productivity",
    ["protonmail", "email", "secure", "mail"],
  ],
  microsoft: ["FA5", "microsoft", "#00A4EF", "productivity", ["microsoft", "windows", "account"]],
  apple: ["FA5", "apple", "#000000", "productivity", ["apple", "icloud", "ios", "mac"]],
  notion: ["MCI", "notebook", "#000000", "productivity", ["notion", "notes", "productivity"]],
  trello: ["FA5", "trello", "#0052CC", "productivity", ["trello", "project", "kanban"]],
  asana: ["MCI", "check-circle", "#F06A6A", "productivity", ["asana", "project", "tasks"]],
  jira: ["MCI", "jira", "#0052CC", "productivity", ["jira", "project", "atlassian", "bugs"]],
  confluence: [
    "MCI",
    "file-document-multiple",
    "#172B4D",
    "productivity",
    ["confluence", "wiki", "atlassian"],
  ],
  todoist: [
    "MCI",
    "checkbox-marked-circle",
    "#E44332",
    "productivity",
    ["todoist", "tasks", "todo"],
  ],
  evernote: ["MCI", "elephant", "#00A82D", "productivity", ["evernote", "notes"]],
  onenote: [
    "MCI",
    "notebook-outline",
    "#7719AA",
    "productivity",
    ["onenote", "notes", "microsoft"],
  ],
  adobecreativecloud: ["MCI", "palette", "#FF0000", "productivity", ["adobe", "creative", "cloud"]],
  adobe: ["MI", "adobe", "#FF0000", "productivity", ["adobe", "creative", "photoshop", "design"]],
  autocad: [
    "MCI",
    "pencil-ruler",
    "#E51050",
    "productivity",
    ["autocad", "cad", "design", "engineering"],
  ],
  canva: ["MCI", "palette-swatch", "#00C4CC", "productivity", ["canva", "design", "graphics"]],
};

const STORAGE: Record<string, CompactIconDef> = {
  dropbox: ["FA5", "dropbox", "#0061FF", "storage", ["dropbox", "cloud", "storage", "files"]],
  googledrive: [
    "FA5",
    "google-drive",
    "#4285F4",
    "storage",
    ["google drive", "drive", "cloud", "storage", "google"],
  ],
  onedrive: [
    "MCI",
    "microsoft-onedrive",
    "#0078D4",
    "storage",
    ["onedrive", "cloud", "storage", "microsoft"],
  ],
  icloud: ["Ion", "cloud", "#3693F3", "storage", ["icloud", "apple", "cloud", "storage"]],
  box: ["MCI", "folder-multiple", "#0061D5", "storage", ["box", "cloud", "storage"]],
  mega: ["MCI", "cloud-lock", "#D9272E", "storage", ["mega", "cloud", "storage", "secure"]],
  pcloud: ["MCI", "cloud", "#20C5F7", "storage", ["pcloud", "cloud", "storage"]],
};

const MEDIA: Record<string, CompactIconDef> = {
  youtube: ["FA5", "youtube", "#FF0000", "media", ["youtube", "video", "google"]],
  spotify: ["FA5", "spotify", "#1DB954", "media", ["spotify", "music", "streaming"]],
  netflix: ["MCI", "netflix", "#E50914", "media", ["netflix", "streaming", "video", "movies"]],
  primevideo: ["MCI", "play-box", "#00A8E1", "media", ["prime", "amazon", "video", "streaming"]],
  amazonprime: ["MCI", "play-box", "#00A8E1", "media", ["prime", "amazon", "video", "streaming"]],
  disneyplus: ["MCI", "movie", "#113CCF", "media", ["disney", "streaming", "video"]],
  hulu: ["MCI", "play-circle", "#1CE783", "media", ["hulu", "streaming", "video"]],
  hbomax: ["MCI", "television-play", "#B834DB", "media", ["hbo", "max", "streaming"]],
  appletvplus: ["FA5", "apple", "#000000", "media", ["apple", "tv", "streaming"]],
  twitch: ["FA5", "twitch", "#9146FF", "media", ["twitch", "streaming", "gaming"]],
  crunchyroll: [
    "MCI",
    "animation-play",
    "#F47521",
    "media",
    ["crunchyroll", "anime", "streaming", "manga"],
  ],
  sonyliv: ["Ion", "play-circle", "#FF3E34", "media", ["sony", "liv", "streaming", "video", "tv"]],
  hotstar: ["MCI", "star", "#1F5BFF", "media", ["hotstar", "disney", "streaming"]],
  myanimelist: [
    "MCI",
    "format-list-bulleted",
    "#2E51A2",
    "media",
    ["myanimelist", "anime", "manga", "tracking"],
  ],
  animetsu: ["MCI", "animation-play", "#FF6B6B", "media", ["animetsu", "anime", "streaming"]],
  soundcloud: ["FA5", "soundcloud", "#FF5500", "media", ["soundcloud", "music", "audio"]],
  deezer: ["MCI", "music", "#FEAA2D", "media", ["deezer", "music", "streaming"]],
  applemusic: ["FA5", "apple", "#FC3C44", "media", ["apple", "music", "streaming"]],
  tidal: ["MCI", "waves", "#000000", "media", ["tidal", "music", "streaming"]],
  audible: ["MCI", "headphones", "#F8991C", "media", ["audible", "audiobooks", "amazon"]],
  kindle: ["MCI", "book-open-page-variant", "#FF9900", "media", ["kindle", "books", "amazon"]],
};

const GAMING: Record<string, CompactIconDef> = {
  steam: ["FA5", "steam", "#171D25", "gaming", ["steam", "gaming", "valve", "pc"]],
  epicgames: ["MCI", "gamepad-variant", "#2F2D2E", "gaming", ["epic", "games", "fortnite"]],
  riotgames: [
    "MCI",
    "gamepad-square",
    "#D13639",
    "gaming",
    ["riot", "games", "valorant", "league", "gaming", "lol"],
  ],
  battlenet: ["MCI", "gamepad-variant", "#00AEFF", "gaming", ["battlenet", "blizzard", "gaming"]],
  origin: ["MCI", "gamepad", "#F56C2D", "gaming", ["origin", "ea", "gaming"]],
  ea: ["MCI", "gamepad-square-outline", "#000000", "gaming", ["ea", "electronic arts", "gaming"]],
  ubisoft: ["MCI", "gamepad-variant-outline", "#0070FF", "gaming", ["ubisoft", "gaming"]],
  playstation: [
    "MCI",
    "sony-playstation",
    "#003791",
    "gaming",
    ["playstation", "sony", "gaming", "ps5"],
  ],
  xbox: ["MCI", "microsoft-xbox", "#107C10", "gaming", ["xbox", "microsoft", "gaming"]],
  nintendo: ["MCI", "nintendo-switch", "#E60012", "gaming", ["nintendo", "switch", "gaming"]],
  gog: ["MCI", "gamepad", "#86328A", "gaming", ["gog", "gaming", "drm-free"]],
  callofduty: [
    "MCI",
    "crosshairs-gps",
    "#000000",
    "gaming",
    ["call of duty", "cod", "gaming", "activision"],
  ],
  chess: ["MCI", "chess-knight", "#81B64C", "gaming", ["chess", "game", "strategy", "chesscom"]],
  lichess: ["MCI", "chess-queen", "#000000", "gaming", ["lichess", "chess", "game"]],
  aternos: ["MCI", "minecraft", "#48A5E6", "gaming", ["aternos", "minecraft", "server", "hosting"]],
  minecraft: ["MCI", "minecraft", "#62B47A", "gaming", ["minecraft", "gaming", "mojang"]],
  roblox: ["MCI", "cube-outline", "#E31B23", "gaming", ["roblox", "gaming"]],
};

const FINANCE: Record<string, CompactIconDef> = {
  paypal: ["FA5", "paypal", "#00457C", "finance", ["paypal", "payment", "money"]],
  stripe: ["FA5", "stripe", "#635BFF", "finance", ["stripe", "payment", "money"]],
  venmo: ["MCI", "cash", "#3D95CE", "finance", ["venmo", "payment", "money"]],
  cashapp: ["MCI", "currency-usd", "#00D632", "finance", ["cashapp", "cash", "payment", "square"]],
  revolut: ["MCI", "bank", "#0075EB", "finance", ["revolut", "banking", "finance"]],
  wise: ["MCI", "bank-transfer", "#00B9FF", "finance", ["wise", "transfer", "money"]],
  paytm: ["MCI", "wallet", "#00B9F5", "finance", ["paytm", "payment", "wallet", "upi", "india"]],
  googlepay: [
    "MCI",
    "google",
    "#4285F4",
    "finance",
    ["google pay", "gpay", "payment", "upi", "wallet"],
  ],
  phonepe: [
    "MCI",
    "cellphone-wireless",
    "#5F259F",
    "finance",
    ["phonepe", "payment", "upi", "wallet", "india"],
  ],
  zerodha: [
    "MCI",
    "chart-line",
    "#387ED1",
    "finance",
    ["zerodha", "trading", "stocks", "broker", "invest"],
  ],
  groww: [
    "MCI",
    "chart-areaspline",
    "#00D09C",
    "finance",
    ["groww", "investment", "stocks", "mutual funds", "trading"],
  ],
  upstox: [
    "MCI",
    "trending-up",
    "#623CE6",
    "finance",
    ["upstox", "trading", "stocks", "broker", "invest"],
  ],
  angelone: [
    "MCI",
    "chart-line-variant",
    "#E32F2F",
    "finance",
    ["angel", "one", "trading", "stocks", "broker"],
  ],
  sharekhan: [
    "MCI",
    "chart-bell-curve",
    "#FF8100",
    "finance",
    ["sharekhan", "trading", "stocks", "broker", "invest"],
  ],
  kite: ["MCI", "kite", "#387ED1", "finance", ["kite", "zerodha", "trading"]],
  robinhood: ["MCI", "leaf", "#00C805", "finance", ["robinhood", "trading", "stocks"]],
  fidelity: ["MCI", "finance", "#498500", "finance", ["fidelity", "investment", "stocks"]],
};

const CRYPTO: Record<string, CompactIconDef> = {
  coinbase: [
    "MCI",
    "bitcoin",
    "#0052FF",
    "crypto",
    ["coinbase", "crypto", "exchange", "wallet", "bitcoin"],
  ],
  binance: [
    "MCI",
    "currency-btc",
    "#F3BA2F",
    "crypto",
    ["binance", "crypto", "exchange", "trading", "bitcoin"],
  ],
  kraken: ["MCI", "octopus", "#5741D9", "crypto", ["kraken", "crypto", "exchange", "trading"]],
  coindcx: [
    "MCI",
    "bitcoin",
    "#FF6B35",
    "crypto",
    ["coindcx", "crypto", "exchange", "trading", "bitcoin", "india"],
  ],
  wazirx: [
    "MCI",
    "ethereum",
    "#3C72DB",
    "crypto",
    ["wazirx", "crypto", "exchange", "trading", "india"],
  ],
  deltaexchange: [
    "FA5",
    "ethereum",
    "#6C5CE7",
    "crypto",
    ["delta", "exchange", "crypto", "trading", "derivatives"],
  ],
  kucoin: ["MCI", "bitcoin", "#23AF91", "crypto", ["kucoin", "crypto", "exchange"]],
  gemini: ["MCI", "currency-btc", "#00DCFA", "crypto", ["gemini", "crypto", "exchange"]],
  metamask: ["MCI", "fox", "#E2761B", "crypto", ["metamask", "wallet", "ethereum", "crypto"]],
  phantom: ["MCI", "ghost", "#AB9FF2", "crypto", ["phantom", "wallet", "solana", "crypto"]],
  ledger: ["MCI", "usb", "#000000", "crypto", ["ledger", "wallet", "hardware", "crypto"]],
  trezor: ["MCI", "shield-key", "#00A84E", "crypto", ["trezor", "wallet", "hardware", "crypto"]],
  poligon: [
    "MCI",
    "hexagon-outline",
    "#8247E5",
    "crypto",
    ["polygon", "poligon", "matic", "blockchain", "crypto", "ethereum"],
  ],
  opensea: ["MCI", "sail-boat", "#2081E2", "crypto", ["opensea", "nft", "marketplace"]],
};

const BANKING: Record<string, CompactIconDef> = {
  bankaccount: [
    "MCI",
    "bank",
    "#2E7D32",
    "banking",
    ["bank", "account", "banking", "savings", "checking"],
  ],
  sbi: ["MCI", "bank", "#003D7A", "banking", ["sbi", "state bank", "india", "bank", "banking"]],
  hdfc: ["MCI", "bank", "#004C8F", "banking", ["hdfc", "bank", "banking", "india"]],
  icici: ["MCI", "bank", "#F37920", "banking", ["icici", "bank", "banking", "india"]],
  axis: ["MCI", "bank", "#97144D", "banking", ["axis", "bank", "banking", "india"]],
  kotak: ["MCI", "bank", "#ED1C24", "banking", ["kotak", "bank", "banking", "india"]],
  pnb: ["MCI", "bank", "#003C7D", "banking", ["pnb", "punjab national", "bank", "india"]],
  bob: ["MCI", "bank", "#F15A22", "banking", ["bob", "bank of baroda", "india"]],
  chase: ["MCI", "bank", "#117ACA", "banking", ["chase", "jpmorgan", "bank", "usa"]],
  bofa: ["MCI", "bank", "#012169", "banking", ["bank of america", "bofa", "usa"]],
  wellsfargo: ["MCI", "bank", "#D71E28", "banking", ["wells fargo", "bank", "usa"]],
  citi: ["MCI", "bank", "#003B70", "banking", ["citi", "citibank", "bank"]],
  barclays: ["MCI", "bank", "#00AEEF", "banking", ["barclays", "bank", "uk"]],
  hsbc: ["MCI", "bank", "#DB0011", "banking", ["hsbc", "bank"]],
};

const IDENTITY: Record<string, CompactIconDef> = {
  aadhar: [
    "MCI",
    "card-account-details",
    "#D32F2F",
    "identity",
    ["aadhar", "aadhaar", "id", "india", "identity", "uid"],
  ],
  aadhaar: [
    "MCI",
    "card-account-details",
    "#D32F2F",
    "identity",
    ["aadhaar", "aadhar", "id", "india", "identity", "uid"],
  ],
  pancard: [
    "MCI",
    "card-text",
    "#1565C0",
    "identity",
    ["pan", "card", "tax", "india", "identity", "income"],
  ],
  voterid: [
    "MCI",
    "vote",
    "#388E3C",
    "identity",
    ["voter", "id", "election", "india", "identity", "card"],
  ],
  passport: [
    "MCI",
    "passport",
    "#0D47A1",
    "identity",
    ["passport", "travel", "identity", "international", "id"],
  ],
  drivinglicense: [
    "MCI",
    "card-account-details-outline",
    "#F57C00",
    "identity",
    ["driving", "license", "dl", "car", "identity", "id"],
  ],
  socialsecurity: [
    "MCI",
    "shield-account",
    "#5E35B1",
    "identity",
    ["ssn", "social security", "identity", "usa", "id"],
  ],
  nationalid: [
    "MCI",
    "card-account-details",
    "#00796B",
    "identity",
    ["national", "id", "identity", "card", "government"],
  ],
  abcid: [
    "MCI",
    "account-box",
    "#4A90E2",
    "identity",
    ["abc", "id", "account", "identity", "academic"],
  ],
  aaplesarkar: [
    "MCI",
    "domain",
    "#FF6B35",
    "identity",
    ["aaple", "sarkar", "maharashtra", "government"],
  ],
  digilocker: [
    "MCI",
    "folder-lock",
    "#1565C0",
    "identity",
    ["digilocker", "documents", "india", "government"],
  ],
  umang: [
    "MCI",
    "cellphone-check",
    "#E65100",
    "identity",
    ["umang", "india", "government", "services"],
  ],
};

const EDUCATION: Record<string, CompactIconDef> = {
  coursera: ["MCI", "school", "#0056D2", "education", ["coursera", "learning", "courses"]],
  udemy: ["MCI", "play-circle", "#A435F0", "education", ["udemy", "learning", "courses"]],
  edx: ["MCI", "school", "#02262B", "education", ["edx", "learning", "courses"]],
  khanacademy: ["MCI", "leaf", "#14BF96", "education", ["khan academy", "learning", "education"]],
  skillshare: [
    "MCI",
    "palette-outline",
    "#00FF84",
    "education",
    ["skillshare", "learning", "creative"],
  ],
  pluralsight: ["MCI", "play-box", "#F15B2A", "education", ["pluralsight", "learning", "tech"]],
  linkedinlearning: [
    "FA5",
    "linkedin",
    "#0A66C2",
    "education",
    ["linkedin", "learning", "courses"],
  ],
  duolingo: ["MCI", "owl", "#58CC02", "education", ["duolingo", "language", "learning"]],
  netacad: [
    "MCI",
    "router-network",
    "#049FD9",
    "education",
    ["netacad", "cisco", "networking", "certification", "ccna"],
  ],
  cisconetacad: [
    "MCI",
    "router-network",
    "#049FD9",
    "education",
    ["cisco", "netacad", "networking", "certification"],
  ],
  rglectures: [
    "MCI",
    "book-open-page-variant",
    "#4A90E2",
    "education",
    ["rg", "lectures", "education", "learning"],
  ],
  lmsportal: [
    "MCI",
    "school-outline",
    "#4A90E2",
    "education",
    ["lms", "portal", "learning", "management", "school"],
  ],
  lms: [
    "MCI",
    "school-outline",
    "#4A90E2",
    "education",
    ["lms", "learning", "management", "school"],
  ],
  nmims: ["MCI", "school", "#003DA5", "education", ["nmims", "university", "education", "college"]],
  moodle: ["MCI", "school", "#F98012", "education", ["moodle", "lms", "learning"]],
  blackboard: ["MCI", "chalkboard", "#262626", "education", ["blackboard", "lms", "learning"]],
  canvas: ["MCI", "format-paint", "#E03E2D", "education", ["canvas", "lms", "learning"]],
};

const SHOPPING: Record<string, CompactIconDef> = {
  amazon: ["FA5", "amazon", "#FF9900", "shopping", ["amazon", "shopping", "ecommerce"]],
  ebay: ["FA5", "ebay", "#E53238", "shopping", ["ebay", "shopping", "auction"]],
  shopify: ["FA5", "shopify", "#7AB55C", "shopping", ["shopify", "ecommerce", "store"]],
  etsy: ["FA5", "etsy", "#F16521", "shopping", ["etsy", "shopping", "handmade"]],
  flipkart: [
    "MCI",
    "shopping",
    "#2874F0",
    "shopping",
    ["flipkart", "shopping", "india", "ecommerce"],
  ],
  myntra: ["MCI", "tshirt-crew", "#FF3F6C", "shopping", ["myntra", "fashion", "shopping", "india"]],
  aliexpress: ["MCI", "shopping", "#E43225", "shopping", ["aliexpress", "shopping", "alibaba"]],
  walmart: ["MCI", "cart", "#0071DC", "shopping", ["walmart", "shopping", "retail"]],
  target: ["MCI", "bullseye", "#CC0000", "shopping", ["target", "shopping", "retail"]],
  bestbuy: ["MCI", "tag", "#0046BE", "shopping", ["bestbuy", "electronics", "shopping"]],
  mcdonalds: [
    "MCI",
    "food",
    "#FFC72C",
    "shopping",
    ["mcdonalds", "food", "restaurant", "fastfood", "burger"],
  ],
  starbucks: ["MCI", "coffee", "#00704A", "shopping", ["starbucks", "coffee", "food"]],
  doordash: ["MCI", "food-takeout-box", "#FF3008", "shopping", ["doordash", "food", "delivery"]],
  ubereats: ["FA5", "uber", "#000000", "shopping", ["ubereats", "food", "delivery"]],
  instacart: ["MCI", "cart", "#43B02A", "shopping", ["instacart", "grocery", "delivery"]],
  swiggy: ["MCI", "food", "#FC8019", "shopping", ["swiggy", "food", "delivery", "india"]],
  zomato: ["MCI", "food", "#E23744", "shopping", ["zomato", "food", "delivery", "india"]],
  cashngifts: [
    "MCI",
    "gift",
    "#FF6B35",
    "shopping",
    ["cashngifts", "rewards", "vouchers", "cashback"],
  ],
  swagbucks: [
    "MCI",
    "cash-multiple",
    "#00B67A",
    "shopping",
    ["swagbucks", "rewards", "cashback", "surveys"],
  ],
  tolunainfluencers: [
    "MCI",
    "poll",
    "#00A1E4",
    "other",
    ["toluna", "surveys", "rewards", "influencers"],
  ],
};

const TRAVEL: Record<string, CompactIconDef> = {
  airbnb: ["FA5", "airbnb", "#FF5A5F", "travel", ["airbnb", "travel", "booking"]],
  uber: ["FA5", "uber", "#000000", "travel", ["uber", "ride", "travel"]],
  lyft: ["FA5", "lyft", "#FF00BF", "travel", ["lyft", "ride", "travel"]],
  booking: ["MCI", "bed", "#003580", "travel", ["booking", "hotel", "travel"]],
  expedia: ["MCI", "airplane", "#00355F", "travel", ["expedia", "travel", "booking"]],
  tripadvisor: ["MCI", "owl", "#34E0A1", "travel", ["tripadvisor", "travel", "reviews"]],
  kayak: ["MCI", "airplane", "#FF690F", "travel", ["kayak", "travel", "flights"]],
  skyscanner: ["MCI", "airplane-search", "#0770E3", "travel", ["skyscanner", "flights", "travel"]],
  makemytrip: ["MCI", "airplane", "#EB2027", "travel", ["makemytrip", "travel", "india"]],
  goibibo: ["MCI", "airplane", "#EC5B24", "travel", ["goibibo", "travel", "india"]],
  ola: ["MCI", "car", "#1C8E41", "travel", ["ola", "ride", "india"]],
  rapido: ["MCI", "motorbike", "#FEDA00", "travel", ["rapido", "ride", "bike", "india"]],
};

const OTHER: Record<string, CompactIconDef> = {
  samsung: ["MCI", "cellphone", "#1428A0", "other", ["samsung", "phone", "galaxy", "account"]],
  marvelinsider: [
    "MCI",
    "shield-star",
    "#ED1D24",
    "other",
    ["marvel", "insider", "rewards", "comics", "avengers"],
  ],
  fiverr: ["MCI", "briefcase", "#1DBF73", "other", ["fiverr", "freelance", "work", "gigs"]],
  upwork: ["MCI", "briefcase-outline", "#14A800", "other", ["upwork", "freelance", "work"]],
  freelancer: ["MCI", "briefcase-variant", "#29B2FE", "other", ["freelancer", "work", "gigs"]],
  medium: ["FA5", "medium", "#000000", "other", ["medium", "blog", "writing"]],
  substack: ["MCI", "email-newsletter", "#FF6719", "other", ["substack", "newsletter", "writing"]],
  wordpress: ["FA5", "wordpress", "#21759B", "other", ["wordpress", "blog", "website"]],
  blogger: ["MCI", "post", "#FF5722", "other", ["blogger", "blog", "google"]],
  tumblr: ["FA5", "tumblr", "#35465C", "other", ["tumblr", "blog", "social"]],
  quora: ["FA5", "quora", "#A82400", "other", ["quora", "qa", "questions"]],
  krea: ["MCI", "creation", "#8B5CF6", "other", ["krea", "ai", "design", "art", "image"]],
  producthunt: ["FA5", "product-hunt", "#DA552F", "other", ["producthunt", "startup", "tech"]],
  dribbble: ["FA5", "dribbble", "#EA4C89", "other", ["dribbble", "design", "portfolio"]],
  behance: ["FA5", "behance", "#1769FF", "other", ["behance", "design", "portfolio", "adobe"]],
  deviantart: ["FA5", "deviantart", "#05CC47", "other", ["deviantart", "art", "portfolio"]],
  artstation: ["MCI", "palette", "#13AFF0", "other", ["artstation", "art", "portfolio"]],
  flickr: ["FA5", "flickr", "#0063DC", "other", ["flickr", "photo", "sharing"]],
  unsplash: ["MCI", "image", "#000000", "other", ["unsplash", "photo", "stock"]],
  pexels: ["MCI", "image-multiple", "#05A081", "other", ["pexels", "photo", "stock"]],
  lastpass: ["MCI", "key-variant", "#D32D27", "other", ["lastpass", "password", "manager"]],
  onepassword: ["MCI", "lock", "#0094F5", "other", ["1password", "password", "manager"]],
  bitwarden: ["MCI", "shield-lock", "#175DDC", "other", ["bitwarden", "password", "manager"]],
  dashlane: ["MCI", "shield-check", "#0E6856", "other", ["dashlane", "password", "manager"]],
  nordvpn: ["MCI", "shield", "#4687FF", "other", ["nordvpn", "vpn", "security"]],
  expressvpn: ["MCI", "shield", "#DA3940", "other", ["expressvpn", "vpn", "security"]],
  surfshark: ["MCI", "shark-fin", "#1ECBCF", "other", ["surfshark", "vpn", "security"]],
  protonvpn: ["MCI", "shield-lock-outline", "#66DEB1", "other", ["protonvpn", "vpn", "security"]],
};

export const COMPACT_PLATFORM_ICONS: Record<string, CompactIconDef> = {
  ...SOCIAL,
  ...COMMUNICATION,
  ...AI,
  ...DEVELOPER,
  ...PRODUCTIVITY,
  ...STORAGE,
  ...MEDIA,
  ...GAMING,
  ...FINANCE,
  ...CRYPTO,
  ...BANKING,
  ...IDENTITY,
  ...EDUCATION,
  ...SHOPPING,
  ...TRAVEL,
  ...OTHER,
};

export const ICON_CATEGORIES_LIST = [
  { id: "social", label: "Social Media", icon: "people" },
  { id: "communication", label: "Communication", icon: "chatbubbles" },
  { id: "ai", label: "AI & Chatbots", icon: "hardware-chip" },
  { id: "developer", label: "Developer Tools", icon: "code" },
  { id: "productivity", label: "Productivity", icon: "briefcase" },
  { id: "storage", label: "Cloud Storage", icon: "cloud" },
  { id: "media", label: "Media & Entertainment", icon: "play" },
  { id: "gaming", label: "Gaming", icon: "game-controller" },
  { id: "finance", label: "Finance & Trading", icon: "trending-up" },
  { id: "crypto", label: "Cryptocurrency", icon: "logo-bitcoin" },
  { id: "banking", label: "Banking", icon: "business" },
  { id: "identity", label: "Identity & Documents", icon: "card" },
  { id: "education", label: "Education", icon: "school" },
  { id: "shopping", label: "Shopping & Food", icon: "cart" },
  { id: "travel", label: "Travel", icon: "airplane" },
  { id: "other", label: "Other", icon: "apps" },
] as const;
