/**
 * Icon Mapping Constants
 * Pre-mapped platform icons using expo-vector-icons
 * Libraries: MaterialIcons, Ionicons, FontAwesome, Feather, AntDesign, Entypo
 */

export interface IconMapping {
  platform: string;
  displayName: string;
  library: 'MaterialIcons' | 'Ionicons' | 'FontAwesome' | 'FontAwesome5' | 'Feather' | 'AntDesign' | 'Entypo' | 'MaterialCommunityIcons';
  iconName: string;
  defaultColor: string;
  category: 'social' | 'productivity' | 'finance' | 'storage' | 'communication' | 'media' | 'developer' | 'shopping' | 'travel' | 'other';
  keywords: string[];
}

export const PLATFORM_ICONS: Record<string, IconMapping> = {
  // Social Media
  facebook: {
    platform: 'facebook',
    displayName: 'Facebook',
    library: 'FontAwesome5',
    iconName: 'facebook',
    defaultColor: '#1877F2',
    category: 'social',
    keywords: ['facebook', 'social', 'meta'],
  },
  instagram: {
    platform: 'instagram',
    displayName: 'Instagram',
    library: 'FontAwesome5',
    iconName: 'instagram',
    defaultColor: '#E4405F',
    category: 'social',
    keywords: ['instagram', 'social', 'photo', 'meta'],
  },
  twitter: {
    platform: 'twitter',
    displayName: 'Twitter / X',
    library: 'FontAwesome5',
    iconName: 'twitter',
    defaultColor: '#1DA1F2',
    category: 'social',
    keywords: ['twitter', 'x', 'social', 'tweet'],
  },
  linkedin: {
    platform: 'linkedin',
    displayName: 'LinkedIn',
    library: 'FontAwesome5',
    iconName: 'linkedin',
    defaultColor: '#0A66C2',
    category: 'social',
    keywords: ['linkedin', 'professional', 'jobs'],
  },
  youtube: {
    platform: 'youtube',
    displayName: 'YouTube',
    library: 'FontAwesome5',
    iconName: 'youtube',
    defaultColor: '#FF0000',
    category: 'media',
    keywords: ['youtube', 'video', 'google'],
  },
  tiktok: {
    platform: 'tiktok',
    displayName: 'TikTok',
    library: 'MaterialCommunityIcons',
    iconName: 'music-note',
    defaultColor: '#000000',
    category: 'social',
    keywords: ['tiktok', 'video', 'social'],
  },
  snapchat: {
    platform: 'snapchat',
    displayName: 'Snapchat',
    library: 'FontAwesome5',
    iconName: 'snapchat',
    defaultColor: '#FFFC00',
    category: 'social',
    keywords: ['snapchat', 'social', 'photo'],
  },
  reddit: {
    platform: 'reddit',
    displayName: 'Reddit',
    library: 'FontAwesome5',
    iconName: 'reddit',
    defaultColor: '#FF4500',
    category: 'social',
    keywords: ['reddit', 'social', 'forum'],
  },
  pinterest: {
    platform: 'pinterest',
    displayName: 'Pinterest',
    library: 'FontAwesome5',
    iconName: 'pinterest',
    defaultColor: '#E60023',
    category: 'social',
    keywords: ['pinterest', 'social', 'images'],
  },
  twitch: {
    platform: 'twitch',
    displayName: 'Twitch',
    library: 'FontAwesome5',
    iconName: 'twitch',
    defaultColor: '#9146FF',
    category: 'media',
    keywords: ['twitch', 'streaming', 'gaming'],
  },

  // Communication
  whatsapp: {
    platform: 'whatsapp',
    displayName: 'WhatsApp',
    library: 'FontAwesome5',
    iconName: 'whatsapp',
    defaultColor: '#25D366',
    category: 'communication',
    keywords: ['whatsapp', 'chat', 'messaging', 'meta'],
  },
  telegram: {
    platform: 'telegram',
    displayName: 'Telegram',
    library: 'FontAwesome5',
    iconName: 'telegram',
    defaultColor: '#0088CC',
    category: 'communication',
    keywords: ['telegram', 'chat', 'messaging'],
  },
  signal: {
    platform: 'signal',
    displayName: 'Signal',
    library: 'MaterialCommunityIcons',
    iconName: 'message-lock',
    defaultColor: '#3A76F0',
    category: 'communication',
    keywords: ['signal', 'chat', 'secure', 'messaging'],
  },
  messenger: {
    platform: 'messenger',
    displayName: 'Messenger',
    library: 'MaterialCommunityIcons',
    iconName: 'facebook-messenger',
    defaultColor: '#0084FF',
    category: 'communication',
    keywords: ['messenger', 'facebook', 'chat', 'meta'],
  },
  wechat: {
    platform: 'wechat',
    displayName: 'WeChat',
    library: 'FontAwesome5',
    iconName: 'weixin',
    defaultColor: '#09B83E',
    category: 'communication',
    keywords: ['wechat', 'weixin', 'chat', 'messaging'],
  },
  discord: {
    platform: 'discord',
    displayName: 'Discord',
    library: 'FontAwesome5',
    iconName: 'discord',
    defaultColor: '#5865F2',
    category: 'communication',
    keywords: ['discord', 'chat', 'gaming', 'community'],
  },
  slack: {
    platform: 'slack',
    displayName: 'Slack',
    library: 'FontAwesome5',
    iconName: 'slack',
    defaultColor: '#4A154B',
    category: 'communication',
    keywords: ['slack', 'work', 'team', 'chat'],
  },
  zoom: {
    platform: 'zoom',
    displayName: 'Zoom',
    library: 'MaterialCommunityIcons',
    iconName: 'video',
    defaultColor: '#2D8CFF',
    category: 'communication',
    keywords: ['zoom', 'video', 'meeting', 'call'],
  },
  skype: {
    platform: 'skype',
    displayName: 'Skype',
    library: 'FontAwesome5',
    iconName: 'skype',
    defaultColor: '#00AFF0',
    category: 'communication',
    keywords: ['skype', 'video', 'call', 'microsoft'],
  },
  teams: {
    platform: 'teams',
    displayName: 'Microsoft Teams',
    library: 'MaterialCommunityIcons',
    iconName: 'microsoft-teams',
    defaultColor: '#6264A7',
    category: 'communication',
    keywords: ['teams', 'microsoft', 'work', 'meeting'],
  },

  // Email & Productivity
  gmail: {
    platform: 'gmail',
    displayName: 'Gmail',
    library: 'MaterialCommunityIcons',
    iconName: 'gmail',
    defaultColor: '#EA4335',
    category: 'productivity',
    keywords: ['gmail', 'email', 'google', 'mail'],
  },
  outlook: {
    platform: 'outlook',
    displayName: 'Outlook',
    library: 'MaterialCommunityIcons',
    iconName: 'microsoft-outlook',
    defaultColor: '#0078D4',
    category: 'productivity',
    keywords: ['outlook', 'email', 'microsoft', 'mail'],
  },
  yahoo: {
    platform: 'yahoo',
    displayName: 'Yahoo Mail',
    library: 'FontAwesome5',
    iconName: 'yahoo',
    defaultColor: '#6001D2',
    category: 'productivity',
    keywords: ['yahoo', 'email', 'mail'],
  },
  protonmail: {
    platform: 'protonmail',
    displayName: 'ProtonMail',
    library: 'MaterialCommunityIcons',
    iconName: 'email-lock',
    defaultColor: '#8B89CC',
    category: 'productivity',
    keywords: ['protonmail', 'email', 'secure', 'mail'],
  },

  // Tech Companies
  google: {
    platform: 'google',
    displayName: 'Google',
    library: 'FontAwesome5',
    iconName: 'google',
    defaultColor: '#4285F4',
    category: 'other',
    keywords: ['google', 'search', 'account'],
  },
  microsoft: {
    platform: 'microsoft',
    displayName: 'Microsoft',
    library: 'FontAwesome5',
    iconName: 'microsoft',
    defaultColor: '#00A4EF',
    category: 'other',
    keywords: ['microsoft', 'windows', 'account'],
  },
  apple: {
    platform: 'apple',
    displayName: 'Apple',
    library: 'FontAwesome5',
    iconName: 'apple',
    defaultColor: '#000000',
    category: 'other',
    keywords: ['apple', 'icloud', 'ios', 'mac'],
  },
  github: {
    platform: 'github',
    displayName: 'GitHub',
    library: 'FontAwesome5',
    iconName: 'github',
    defaultColor: '#181717',
    category: 'developer',
    keywords: ['github', 'git', 'code', 'developer'],
  },
  gitlab: {
    platform: 'gitlab',
    displayName: 'GitLab',
    library: 'FontAwesome5',
    iconName: 'gitlab',
    defaultColor: '#FC6D26',
    category: 'developer',
    keywords: ['gitlab', 'git', 'code', 'developer'],
  },
  bitbucket: {
    platform: 'bitbucket',
    displayName: 'Bitbucket',
    library: 'FontAwesome5',
    iconName: 'bitbucket',
    defaultColor: '#0052CC',
    category: 'developer',
    keywords: ['bitbucket', 'git', 'code', 'developer'],
  },

  // Finance & Payment
  paypal: {
    platform: 'paypal',
    displayName: 'PayPal',
    library: 'FontAwesome5',
    iconName: 'paypal',
    defaultColor: '#00457C',
    category: 'finance',
    keywords: ['paypal', 'payment', 'money'],
  },
  stripe: {
    platform: 'stripe',
    displayName: 'Stripe',
    library: 'FontAwesome5',
    iconName: 'stripe',
    defaultColor: '#635BFF',
    category: 'finance',
    keywords: ['stripe', 'payment', 'money'],
  },
  venmo: {
    platform: 'venmo',
    displayName: 'Venmo',
    library: 'MaterialCommunityIcons',
    iconName: 'cash',
    defaultColor: '#3D95CE',
    category: 'finance',
    keywords: ['venmo', 'payment', 'money'],
  },
  cashapp: {
    platform: 'cashapp',
    displayName: 'Cash App',
    library: 'MaterialCommunityIcons',
    iconName: 'currency-usd',
    defaultColor: '#00D632',
    category: 'finance',
    keywords: ['cashapp', 'cash', 'payment', 'square'],
  },
  revolut: {
    platform: 'revolut',
    displayName: 'Revolut',
    library: 'MaterialCommunityIcons',
    iconName: 'bank',
    defaultColor: '#0075EB',
    category: 'finance',
    keywords: ['revolut', 'banking', 'finance'],
  },

  // Cloud Storage
  dropbox: {
    platform: 'dropbox',
    displayName: 'Dropbox',
    library: 'FontAwesome5',
    iconName: 'dropbox',
    defaultColor: '#0061FF',
    category: 'storage',
    keywords: ['dropbox', 'cloud', 'storage', 'files'],
  },
  googledrive: {
    platform: 'googledrive',
    displayName: 'Google Drive',
    library: 'FontAwesome5',
    iconName: 'google-drive',
    defaultColor: '#4285F4',
    category: 'storage',
    keywords: ['google drive', 'drive', 'cloud', 'storage', 'google'],
  },
  onedrive: {
    platform: 'onedrive',
    displayName: 'OneDrive',
    library: 'MaterialCommunityIcons',
    iconName: 'microsoft-onedrive',
    defaultColor: '#0078D4',
    category: 'storage',
    keywords: ['onedrive', 'cloud', 'storage', 'microsoft'],
  },
  icloud: {
    platform: 'icloud',
    displayName: 'iCloud',
    library: 'Ionicons',
    iconName: 'cloud',
    defaultColor: '#3693F3',
    category: 'storage',
    keywords: ['icloud', 'apple', 'cloud', 'storage'],
  },
  box: {
    platform: 'box',
    displayName: 'Box',
    library: 'MaterialCommunityIcons',
    iconName: 'folder-multiple',
    defaultColor: '#0061D5',
    category: 'storage',
    keywords: ['box', 'cloud', 'storage'],
  },

  // Productivity & Work
  notion: {
    platform: 'notion',
    displayName: 'Notion',
    library: 'MaterialCommunityIcons',
    iconName: 'notebook',
    defaultColor: '#000000',
    category: 'productivity',
    keywords: ['notion', 'notes', 'productivity'],
  },
  trello: {
    platform: 'trello',
    displayName: 'Trello',
    library: 'FontAwesome5',
    iconName: 'trello',
    defaultColor: '#0052CC',
    category: 'productivity',
    keywords: ['trello', 'project', 'kanban'],
  },
  asana: {
    platform: 'asana',
    displayName: 'Asana',
    library: 'MaterialCommunityIcons',
    iconName: 'check-circle',
    defaultColor: '#F06A6A',
    category: 'productivity',
    keywords: ['asana', 'project', 'tasks'],
  },
  jira: {
    platform: 'jira',
    displayName: 'Jira',
    library: 'MaterialCommunityIcons',
    iconName: 'jira',
    defaultColor: '#0052CC',
    category: 'productivity',
    keywords: ['jira', 'project', 'atlassian', 'bugs'],
  },
  confluence: {
    platform: 'confluence',
    displayName: 'Confluence',
    library: 'MaterialCommunityIcons',
    iconName: 'file-document-multiple',
    defaultColor: '#172B4D',
    category: 'productivity',
    keywords: ['confluence', 'wiki', 'atlassian'],
  },
  figma: {
    platform: 'figma',
    displayName: 'Figma',
    library: 'FontAwesome5',
    iconName: 'figma',
    defaultColor: '#F24E1E',
    category: 'productivity',
    keywords: ['figma', 'design', 'ui', 'ux'],
  },

  // Shopping & E-commerce
  amazon: {
    platform: 'amazon',
    displayName: 'Amazon',
    library: 'FontAwesome5',
    iconName: 'amazon',
    defaultColor: '#FF9900',
    category: 'shopping',
    keywords: ['amazon', 'shopping', 'ecommerce'],
  },
  ebay: {
    platform: 'ebay',
    displayName: 'eBay',
    library: 'FontAwesome5',
    iconName: 'ebay',
    defaultColor: '#E53238',
    category: 'shopping',
    keywords: ['ebay', 'shopping', 'auction'],
  },
  shopify: {
    platform: 'shopify',
    displayName: 'Shopify',
    library: 'FontAwesome5',
    iconName: 'shopify',
    defaultColor: '#7AB55C',
    category: 'shopping',
    keywords: ['shopify', 'ecommerce', 'store'],
  },
  etsy: {
    platform: 'etsy',
    displayName: 'Etsy',
    library: 'FontAwesome5',
    iconName: 'etsy',
    defaultColor: '#F16521',
    category: 'shopping',
    keywords: ['etsy', 'shopping', 'handmade'],
  },

  // Media & Entertainment
  spotify: {
    platform: 'spotify',
    displayName: 'Spotify',
    library: 'FontAwesome5',
    iconName: 'spotify',
    defaultColor: '#1DB954',
    category: 'media',
    keywords: ['spotify', 'music', 'streaming'],
  },
  netflix: {
    platform: 'netflix',
    displayName: 'Netflix',
    library: 'MaterialCommunityIcons',
    iconName: 'netflix',
    defaultColor: '#E50914',
    category: 'media',
    keywords: ['netflix', 'streaming', 'video', 'movies'],
  },
  hulu: {
    platform: 'hulu',
    displayName: 'Hulu',
    library: 'MaterialCommunityIcons',
    iconName: 'play-circle',
    defaultColor: '#1CE783',
    category: 'media',
    keywords: ['hulu', 'streaming', 'video'],
  },
  prime: {
    platform: 'prime',
    displayName: 'Prime Video',
    library: 'MaterialCommunityIcons',
    iconName: 'play-box',
    defaultColor: '#00A8E1',
    category: 'media',
    keywords: ['prime', 'amazon', 'video', 'streaming'],
  },
  disney: {
    platform: 'disney',
    displayName: 'Disney+',
    library: 'MaterialCommunityIcons',
    iconName: 'movie',
    defaultColor: '#113CCF',
    category: 'media',
    keywords: ['disney', 'streaming', 'video'],
  },

  // Travel
  airbnb: {
    platform: 'airbnb',
    displayName: 'Airbnb',
    library: 'FontAwesome5',
    iconName: 'airbnb',
    defaultColor: '#FF5A5F',
    category: 'travel',
    keywords: ['airbnb', 'travel', 'booking'],
  },
  uber: {
    platform: 'uber',
    displayName: 'Uber',
    library: 'FontAwesome5',
    iconName: 'uber',
    defaultColor: '#000000',
    category: 'travel',
    keywords: ['uber', 'ride', 'travel'],
  },
  lyft: {
    platform: 'lyft',
    displayName: 'Lyft',
    library: 'FontAwesome5',
    iconName: 'lyft',
    defaultColor: '#FF00BF',
    category: 'travel',
    keywords: ['lyft', 'ride', 'travel'],
  },
  booking: {
    platform: 'booking',
    displayName: 'Booking.com',
    library: 'MaterialCommunityIcons',
    iconName: 'bed',
    defaultColor: '#003580',
    category: 'travel',
    keywords: ['booking', 'hotel', 'travel'],
  },

  // Developer Tools
  stackoverflow: {
    platform: 'stackoverflow',
    displayName: 'Stack Overflow',
    library: 'FontAwesome5',
    iconName: 'stack-overflow',
    defaultColor: '#F58025',
    category: 'developer',
    keywords: ['stackoverflow', 'developer', 'code', 'questions'],
  },
  npm: {
    platform: 'npm',
    displayName: 'NPM',
    library: 'FontAwesome5',
    iconName: 'npm',
    defaultColor: '#CB3837',
    category: 'developer',
    keywords: ['npm', 'node', 'package', 'developer'],
  },
  docker: {
    platform: 'docker',
    displayName: 'Docker',
    library: 'MaterialCommunityIcons',
    iconName: 'docker',
    defaultColor: '#2496ED',
    category: 'developer',
    keywords: ['docker', 'container', 'developer'],
  },
  aws: {
    platform: 'aws',
    displayName: 'AWS',
    library: 'FontAwesome5',
    iconName: 'aws',
    defaultColor: '#FF9900',
    category: 'developer',
    keywords: ['aws', 'amazon', 'cloud', 'developer'],
  },
};

// Helper arrays for categorization
export const ICON_CATEGORIES = [
  { id: 'social', label: 'Social Media', icon: 'people' },
  { id: 'communication', label: 'Communication', icon: 'chatbubbles' },
  { id: 'productivity', label: 'Productivity', icon: 'briefcase' },
  { id: 'finance', label: 'Finance', icon: 'card' },
  { id: 'storage', label: 'Cloud Storage', icon: 'cloud' },
  { id: 'media', label: 'Media', icon: 'play' },
  { id: 'shopping', label: 'Shopping', icon: 'cart' },
  { id: 'travel', label: 'Travel', icon: 'airplane' },
  { id: 'developer', label: 'Developer', icon: 'code' },
  { id: 'other', label: 'Other', icon: 'apps' },
] as const;

// Predefined color palette
export const ICON_COLOR_PALETTE = [
  { name: 'Red', value: '#F44336' },
  { name: 'Pink', value: '#E91E63' },
  { name: 'Purple', value: '#9C27B0' },
  { name: 'Deep Purple', value: '#673AB7' },
  { name: 'Indigo', value: '#3F51B5' },
  { name: 'Blue', value: '#2196F3' },
  { name: 'Light Blue', value: '#03A9F4' },
  { name: 'Cyan', value: '#00BCD4' },
  { name: 'Teal', value: '#009688' },
  { name: 'Green', value: '#4CAF50' },
  { name: 'Light Green', value: '#8BC34A' },
  { name: 'Lime', value: '#CDDC39' },
  { name: 'Yellow', value: '#FFEB3B' },
  { name: 'Amber', value: '#FFC107' },
  { name: 'Orange', value: '#FF9800' },
  { name: 'Deep Orange', value: '#FF5722' },
  { name: 'Brown', value: '#795548' },
  { name: 'Grey', value: '#9E9E9E' },
  { name: 'Blue Grey', value: '#607D8B' },
  { name: 'Black', value: '#000000' },
];

// Get all platform icons as array
export const getAllPlatformIcons = (): IconMapping[] => {
  return Object.values(PLATFORM_ICONS);
};

// Get icons by category
export const getIconsByCategory = (category: IconMapping['category']): IconMapping[] => {
  return getAllPlatformIcons().filter(icon => icon.category === category);
};

// Get platform count
export const getPlatformCount = (): number => {
  return Object.keys(PLATFORM_ICONS).length;
};
