// src/constants/iconMapping.ts

export interface IconMapping {
  platform: string;
  displayName: string;
  library:
    | "MaterialIcons"
    | "Ionicons"
    | "FontAwesome"
    | "FontAwesome5"
    | "Feather"
    | "AntDesign"
    | "Entypo"
    | "MaterialCommunityIcons";
  iconName: string;
  defaultColor: string;
  category:
    | "social"
    | "productivity"
    | "finance"
    | "storage"
    | "communication"
    | "media"
    | "developer"
    | "shopping"
    | "travel"
    | "gaming"
    | "education"
    | "identity"
    | "crypto"
    | "banking"
    | "other";
  keywords: string[];
}

export const PLATFORM_ICONS: Record<string, IconMapping> = {
  google: {
    platform: "google",
    displayName: "Google",
    library: "FontAwesome5",
    iconName: "google",
    defaultColor: "#4285F4",
    category: "other",
    keywords: ["google", "search", "account"],
  },
  adobe: {
    platform: "adobe",
    displayName: "Adobe",
    library: "MaterialCommunityIcons",
    iconName: "adobe",
    defaultColor: "#FF0000",
    category: "productivity",
    keywords: ["adobe", "creative", "photoshop", "design"],
  },
  sonyliv: {
    platform: "sonyliv",
    displayName: "Sony Liv",
    library: "Ionicons",
    iconName: "play-circle",
    defaultColor: "#FF3E34",
    category: "media",
    keywords: ["sony", "liv", "streaming", "video", "tv"],
  },
  marvelinsider: {
    platform: "marvelinsider",
    displayName: "Marvel Insider",
    library: "MaterialCommunityIcons",
    iconName: "shield-star",
    defaultColor: "#ED1D24",
    category: "other",
    keywords: ["marvel", "insider", "rewards", "comics"],
  },
  microsoft: {
    platform: "microsoft",
    displayName: "Microsoft",
    library: "FontAwesome5",
    iconName: "microsoft",
    defaultColor: "#00A4EF",
    category: "other",
    keywords: ["microsoft", "windows", "account"],
  },
  samsung: {
    platform: "samsung",
    displayName: "Samsung",
    library: "MaterialCommunityIcons",
    iconName: "cellphone",
    defaultColor: "#1428A0",
    category: "other",
    keywords: ["samsung", "phone", "galaxy", "account"],
  },
  instagram: {
    platform: "instagram",
    displayName: "Instagram",
    library: "FontAwesome5",
    iconName: "instagram",
    defaultColor: "#E4405F",
    category: "social",
    keywords: ["instagram", "social", "photo", "meta"],
  },
  cashngifts: {
    platform: "cashngifts",
    displayName: "Cashngifts",
    library: "MaterialCommunityIcons",
    iconName: "gift",
    defaultColor: "#FF6B35",
    category: "shopping",
    keywords: ["cashngifts", "rewards", "vouchers", "cashback"],
  },
  mega: {
    platform: "mega",
    displayName: "Mega",
    library: "MaterialCommunityIcons",
    iconName: "cloud-lock",
    defaultColor: "#D9272E",
    category: "storage",
    keywords: ["mega", "cloud", "storage", "secure"],
  },
  facebook: {
    platform: "facebook",
    displayName: "Facebook",
    library: "FontAwesome5",
    iconName: "facebook",
    defaultColor: "#1877F2",
    category: "social",
    keywords: ["facebook", "social", "meta"],
  },
  swagbucks: {
    platform: "swagbucks",
    displayName: "Swagbucks",
    library: "MaterialCommunityIcons",
    iconName: "cash-multiple",
    defaultColor: "#00B67A",
    category: "shopping",
    keywords: ["swagbucks", "rewards", "cashback", "surveys"],
  },
  tolunainfluencers: {
    platform: "tolunainfluencers",
    displayName: "Toluna Influencers",
    library: "MaterialCommunityIcons",
    iconName: "poll",
    defaultColor: "#00A1E4",
    category: "other",
    keywords: ["toluna", "surveys", "rewards", "influencers"],
  },
  callofduty: {
    platform: "callofduty",
    displayName: "Call Of Duty",
    library: "MaterialCommunityIcons",
    iconName: "target",
    defaultColor: "#000000",
    category: "gaming",
    keywords: ["call of duty", "cod", "gaming", "activision"],
  },
  crunchyroll: {
    platform: "crunchyroll",
    displayName: "Crunchyroll",
    library: "MaterialCommunityIcons",
    iconName: "television-play",
    defaultColor: "#F47521",
    category: "media",
    keywords: ["crunchyroll", "anime", "streaming", "manga"],
  },
  polygon: {
    platform: "polygon",
    displayName: "Polygon",
    library: "MaterialCommunityIcons",
    iconName: "triangle",
    defaultColor: "#8247E5",
    category: "crypto",
    keywords: ["polygon", "matic", "blockchain", "crypto"],
  },
  krea: {
    platform: "krea",
    displayName: "Krea",
    library: "MaterialCommunityIcons",
    iconName: "palette",
    defaultColor: "#8B5CF6",
    category: "productivity",
    keywords: ["krea", "ai", "design", "art"],
  },
  snapchat: {
    platform: "snapchat",
    displayName: "Snapchat",
    library: "FontAwesome5",
    iconName: "snapchat",
    defaultColor: "#FFFC00",
    category: "social",
    keywords: ["snapchat", "social", "photo"],
  },
  spotify: {
    platform: "spotify",
    displayName: "Spotify",
    library: "FontAwesome5",
    iconName: "spotify",
    defaultColor: "#1DB954",
    category: "media",
    keywords: ["spotify", "music", "streaming"],
  },
  chess: {
    platform: "chess",
    displayName: "Chess",
    library: "MaterialCommunityIcons",
    iconName: "chess-knight",
    defaultColor: "#81B64C",
    category: "gaming",
    keywords: ["chess", "game", "strategy", "chesscom"],
  },
  hellotalk: {
    platform: "hellotalk",
    displayName: "Hellotalk",
    library: "MaterialCommunityIcons",
    iconName: "chat-processing",
    defaultColor: "#0099FF",
    category: "communication",
    keywords: ["hellotalk", "language", "learning", "chat"],
  },
  x: {
    platform: "x",
    displayName: "X",
    library: "FontAwesome5",
    iconName: "twitter",
    defaultColor: "#000000",
    category: "social",
    keywords: ["x", "twitter", "social", "tweet"],
  },
  discord: {
    platform: "discord",
    displayName: "Discord",
    library: "FontAwesome5",
    iconName: "discord",
    defaultColor: "#5865F2",
    category: "communication",
    keywords: ["discord", "chat", "gaming", "community"],
  },
  telegram: {
    platform: "telegram",
    displayName: "Telegram",
    library: "FontAwesome5",
    iconName: "telegram",
    defaultColor: "#0088CC",
    category: "communication",
    keywords: ["telegram", "chat", "messaging"],
  },
  riotgames: {
    platform: "riotgames",
    displayName: "Riot Games",
    library: "MaterialCommunityIcons",
    iconName: "sword-cross",
    defaultColor: "#D13639",
    category: "gaming",
    keywords: ["riot", "games", "valorant", "league", "gaming"],
  },
  steam: {
    platform: "steam",
    displayName: "Steam",
    library: "FontAwesome5",
    iconName: "steam",
    defaultColor: "#171D25",
    category: "gaming",
    keywords: ["steam", "gaming", "valve", "pc"],
  },
  fiverr: {
    platform: "fiverr",
    displayName: "Fiverr",
    library: "MaterialCommunityIcons",
    iconName: "briefcase",
    defaultColor: "#1DBF73",
    category: "other",
    keywords: ["fiverr", "freelance", "work", "gigs"],
  },
  aaplesarkar: {
    platform: "aaplesarkar",
    displayName: "Aaple Sarkar",
    library: "MaterialCommunityIcons",
    iconName: "bank",
    defaultColor: "#FF6B35",
    category: "other",
    keywords: ["aaple", "sarkar", "maharashtra", "government"],
  },
  rglectures: {
    platform: "rglectures",
    displayName: "Rg Lectures",
    library: "MaterialCommunityIcons",
    iconName: "book-open-page-variant",
    defaultColor: "#4A90E2",
    category: "education",
    keywords: ["rg", "lectures", "education", "learning"],
  },
  aternos: {
    platform: "aternos",
    displayName: "Aternos",
    library: "MaterialCommunityIcons",
    iconName: "minecraft",
    defaultColor: "#48A5E6",
    category: "gaming",
    keywords: ["aternos", "minecraft", "server", "hosting"],
  },
  netlify: {
    platform: "netlify",
    displayName: "Netlify",
    library: "MaterialCommunityIcons",
    iconName: "web",
    defaultColor: "#00C7B7",
    category: "developer",
    keywords: ["netlify", "hosting", "deployment", "web"],
  },
  github: {
    platform: "github",
    displayName: "Github",
    library: "FontAwesome5",
    iconName: "github",
    defaultColor: "#181717",
    category: "developer",
    keywords: ["github", "git", "code", "developer"],
  },
  leetcode: {
    platform: "leetcode",
    displayName: "Leetcode",
    library: "MaterialCommunityIcons",
    iconName: "code-braces",
    defaultColor: "#FFA116",
    category: "developer",
    keywords: ["leetcode", "coding", "interview", "algorithm"],
  },
  codechef: {
    platform: "codechef",
    displayName: "Codechef",
    library: "MaterialCommunityIcons",
    iconName: "chef-hat",
    defaultColor: "#5B4638",
    category: "developer",
    keywords: ["codechef", "coding", "competitive", "programming"],
  },
  linkedin: {
    platform: "linkedin",
    displayName: "Linkedin",
    library: "FontAwesome5",
    iconName: "linkedin",
    defaultColor: "#0A66C2",
    category: "social",
    keywords: ["linkedin", "professional", "jobs"],
  },
  autocad: {
    platform: "autocad",
    displayName: "Autocad",
    library: "MaterialCommunityIcons",
    iconName: "pencil-ruler",
    defaultColor: "#E51050",
    category: "productivity",
    keywords: ["autocad", "cad", "design", "engineering"],
  },
  abcid: {
    platform: "abcid",
    displayName: "Abc Id",
    library: "MaterialCommunityIcons",
    iconName: "card-account-details",
    defaultColor: "#4A90E2",
    category: "other",
    keywords: ["abc", "id", "account", "identity"],
  },
  nmims: {
    platform: "nmims",
    displayName: "Nmims",
    library: "MaterialCommunityIcons",
    iconName: "school",
    defaultColor: "#003DA5",
    category: "education",
    keywords: ["nmims", "university", "education", "college"],
  },
  mcdonalds: {
    platform: "mcdonalds",
    displayName: "Mcdonald's",
    library: "MaterialCommunityIcons",
    iconName: "food",
    defaultColor: "#FFC72C",
    category: "shopping",
    keywords: ["mcdonalds", "food", "restaurant", "fastfood"],
  },
  cloudinary: {
    platform: "cloudinary",
    displayName: "Cloudinary",
    library: "MaterialCommunityIcons",
    iconName: "cloud-upload",
    defaultColor: "#3448C5",
    category: "developer",
    keywords: ["cloudinary", "cloud", "images", "media"],
  },
  render: {
    platform: "render",
    displayName: "Render",
    library: "MaterialCommunityIcons",
    iconName: "server",
    defaultColor: "#46E3B7",
    category: "developer",
    keywords: ["render", "hosting", "deployment", "cloud"],
  },
  twitch: {
    platform: "twitch",
    displayName: "Twitch",
    library: "FontAwesome5",
    iconName: "twitch",
    defaultColor: "#9146FF",
    category: "media",
    keywords: ["twitch", "streaming", "gaming"],
  },
  reddit: {
    platform: "reddit",
    displayName: "Reddit",
    library: "FontAwesome5",
    iconName: "reddit",
    defaultColor: "#FF4500",
    category: "social",
    keywords: ["reddit", "social", "forum"],
  },
  myanimelist: {
    platform: "myanimelist",
    displayName: "Myanimelist",
    library: "MaterialCommunityIcons",
    iconName: "movie-open",
    defaultColor: "#2E51A2",
    category: "media",
    keywords: ["myanimelist", "anime", "manga", "tracking"],
  },
  amazon: {
    platform: "amazon",
    displayName: "Amazon",
    library: "FontAwesome5",
    iconName: "amazon",
    defaultColor: "#FF9900",
    category: "shopping",
    keywords: ["amazon", "shopping", "ecommerce"],
  },

  aws: {
    platform: "aws",
    displayName: "AWS",
    library: "FontAwesome5",
    iconName: "aws",
    defaultColor: "#FF9900",
    category: "developer",
    keywords: ["aws", "amazon", "cloud", "developer", "hosting"],
  },
  zerodha: {
    platform: "zerodha",
    displayName: "Zerodha",
    library: "MaterialCommunityIcons",
    iconName: "chart-line",
    defaultColor: "#387ED1",
    category: "finance",
    keywords: ["zerodha", "trading", "stocks", "broker", "invest"],
  },
  coin: {
    platform: "coin",
    displayName: "Coin",
    library: "MaterialCommunityIcons",
    iconName: "bitcoin",
    defaultColor: "#F7931A",
    category: "crypto",
    keywords: ["coin", "crypto", "bitcoin", "zerodha", "trading"],
  },
  deltaexchange: {
    platform: "deltaexchange",
    displayName: "Delta Exchange",
    library: "MaterialCommunityIcons",
    iconName: "delta",
    defaultColor: "#6C5CE7",
    category: "crypto",
    keywords: ["delta", "exchange", "crypto", "trading", "derivatives"],
  },
  coindcx: {
    platform: "coindcx",
    displayName: "CoinDCX",
    library: "MaterialCommunityIcons",
    iconName: "cash-multiple",
    defaultColor: "#FF6B35",
    category: "crypto",
    keywords: ["coindcx", "crypto", "exchange", "trading", "bitcoin"],
  },
  wazirx: {
    platform: "wazirx",
    displayName: "WazirX",
    library: "MaterialCommunityIcons",
    iconName: "ethereum",
    defaultColor: "#3C72DB",
    category: "crypto",
    keywords: ["wazirx", "crypto", "exchange", "trading", "india"],
  },
  binance: {
    platform: "binance",
    displayName: "Binance",
    library: "MaterialCommunityIcons",
    iconName: "currency-btc",
    defaultColor: "#F3BA2F",
    category: "crypto",
    keywords: ["binance", "crypto", "exchange", "trading", "bitcoin"],
  },
  coinbase: {
    platform: "coinbase",
    displayName: "Coinbase",
    library: "MaterialCommunityIcons",
    iconName: "bitcoin",
    defaultColor: "#0052FF",
    category: "crypto",
    keywords: ["coinbase", "crypto", "exchange", "wallet", "bitcoin"],
  },
  kraken: {
    platform: "kraken",
    displayName: "Kraken",
    library: "MaterialCommunityIcons",
    iconName: "waves",
    defaultColor: "#5741D9",
    category: "crypto",
    keywords: ["kraken", "crypto", "exchange", "trading"],
  },

  bankaccount: {
    platform: "bankaccount",
    displayName: "Bank Account",
    library: "MaterialCommunityIcons",
    iconName: "bank",
    defaultColor: "#2E7D32",
    category: "banking",
    keywords: ["bank", "account", "banking", "savings", "checking"],
  },
  sbi: {
    platform: "sbi",
    displayName: "SBI",
    library: "MaterialCommunityIcons",
    iconName: "bank",
    defaultColor: "#003D7A",
    category: "banking",
    keywords: ["sbi", "state bank", "india", "bank", "banking"],
  },
  hdfc: {
    platform: "hdfc",
    displayName: "HDFC Bank",
    library: "MaterialCommunityIcons",
    iconName: "bank",
    defaultColor: "#004C8F",
    category: "banking",
    keywords: ["hdfc", "bank", "banking", "india"],
  },
  icici: {
    platform: "icici",
    displayName: "ICICI Bank",
    library: "MaterialCommunityIcons",
    iconName: "bank",
    defaultColor: "#F37920",
    category: "banking",
    keywords: ["icici", "bank", "banking", "india"],
  },
  axis: {
    platform: "axis",
    displayName: "Axis Bank",
    library: "MaterialCommunityIcons",
    iconName: "bank",
    defaultColor: "#97144D",
    category: "banking",
    keywords: ["axis", "bank", "banking", "india"],
  },
  paytm: {
    platform: "paytm",
    displayName: "Paytm",
    library: "MaterialCommunityIcons",
    iconName: "wallet",
    defaultColor: "#00B9F5",
    category: "finance",
    keywords: ["paytm", "payment", "wallet", "upi", "india"],
  },
  googlepay: {
    platform: "googlepay",
    displayName: "Google Pay",
    library: "MaterialCommunityIcons",
    iconName: "google-pay",
    defaultColor: "#4285F4",
    category: "finance",
    keywords: ["google pay", "gpay", "payment", "upi", "wallet"],
  },
  phonepe: {
    platform: "phonepe",
    displayName: "PhonePe",
    library: "MaterialCommunityIcons",
    iconName: "cellphone-wireless",
    defaultColor: "#5F259F",
    category: "finance",
    keywords: ["phonepe", "payment", "upi", "wallet", "india"],
  },

  aadhar: {
    platform: "aadhar",
    displayName: "Aadhar",
    library: "MaterialCommunityIcons",
    iconName: "card-account-details",
    defaultColor: "#D32F2F",
    category: "identity",
    keywords: ["aadhar", "aadhaar", "id", "india", "identity", "uid"],
  },
  aadhaar: {
    platform: "aadhaar",
    displayName: "Aadhaar",
    library: "MaterialCommunityIcons",
    iconName: "card-account-details",
    defaultColor: "#D32F2F",
    category: "identity",
    keywords: ["aadhaar", "aadhar", "id", "india", "identity", "uid"],
  },
  pancard: {
    platform: "pancard",
    displayName: "PAN Card",
    library: "MaterialCommunityIcons",
    iconName: "card-text",
    defaultColor: "#1565C0",
    category: "identity",
    keywords: ["pan", "card", "tax", "india", "identity", "income"],
  },
  voterid: {
    platform: "voterid",
    displayName: "Voter ID",
    library: "MaterialCommunityIcons",
    iconName: "vote",
    defaultColor: "#388E3C",
    category: "identity",
    keywords: ["voter", "id", "election", "india", "identity", "card"],
  },
  passport: {
    platform: "passport",
    displayName: "Passport",
    library: "MaterialCommunityIcons",
    iconName: "passport",
    defaultColor: "#0D47A1",
    category: "identity",
    keywords: ["passport", "travel", "identity", "international", "id"],
  },
  drivinglicense: {
    platform: "drivinglicense",
    displayName: "Driving License",
    library: "MaterialCommunityIcons",
    iconName: "card-account-details",
    defaultColor: "#F57C00",
    category: "identity",
    keywords: ["driving", "license", "dl", "car", "identity", "id"],
  },
  socialsecurity: {
    platform: "socialsecurity",
    displayName: "Social Security",
    library: "MaterialCommunityIcons",
    iconName: "shield-account",
    defaultColor: "#5E35B1",
    category: "identity",
    keywords: ["ssn", "social security", "identity", "usa", "id"],
  },
  nationalid: {
    platform: "nationalid",
    displayName: "National ID",
    library: "MaterialCommunityIcons",
    iconName: "card-account-details",
    defaultColor: "#00796B",
    category: "identity",
    keywords: ["national", "id", "identity", "card", "government"],
  },

  groww: {
    platform: "groww",
    displayName: "Groww",
    library: "MaterialCommunityIcons",
    iconName: "chart-areaspline",
    defaultColor: "#00D09C",
    category: "finance",
    keywords: ["groww", "investment", "stocks", "mutual funds", "trading"],
  },
  upstox: {
    platform: "upstox",
    displayName: "Upstox",
    library: "MaterialCommunityIcons",
    iconName: "trending-up",
    defaultColor: "#623CE6",
    category: "finance",
    keywords: ["upstox", "trading", "stocks", "broker", "invest"],
  },
  angelone: {
    platform: "angelone",
    displayName: "Angel One",
    library: "MaterialCommunityIcons",
    iconName: "chart-line-variant",
    defaultColor: "#E32F2F",
    category: "finance",
    keywords: ["angel", "one", "trading", "stocks", "broker"],
  },
  sharekhan: {
    platform: "sharekhan",
    displayName: "Sharekhan",
    library: "MaterialCommunityIcons",
    iconName: "chart-bell-curve",
    defaultColor: "#FF8100",
    category: "finance",
    keywords: ["sharekhan", "trading", "stocks", "broker", "invest"],
  },

  twitter: {
    platform: "twitter",
    displayName: "Twitter / X",
    library: "FontAwesome5",
    iconName: "twitter",
    defaultColor: "#1DA1F2",
    category: "social",
    keywords: ["twitter", "x", "social", "tweet"],
  },
  youtube: {
    platform: "youtube",
    displayName: "YouTube",
    library: "FontAwesome5",
    iconName: "youtube",
    defaultColor: "#FF0000",
    category: "media",
    keywords: ["youtube", "video", "google"],
  },
  tiktok: {
    platform: "tiktok",
    displayName: "TikTok",
    library: "MaterialCommunityIcons",
    iconName: "music-note",
    defaultColor: "#000000",
    category: "social",
    keywords: ["tiktok", "video", "social"],
  },
  pinterest: {
    platform: "pinterest",
    displayName: "Pinterest",
    library: "FontAwesome5",
    iconName: "pinterest",
    defaultColor: "#E60023",
    category: "social",
    keywords: ["pinterest", "social", "images"],
  },
  whatsapp: {
    platform: "whatsapp",
    displayName: "WhatsApp",
    library: "FontAwesome5",
    iconName: "whatsapp",
    defaultColor: "#25D366",
    category: "communication",
    keywords: ["whatsapp", "chat", "messaging", "meta"],
  },
  signal: {
    platform: "signal",
    displayName: "Signal",
    library: "MaterialCommunityIcons",
    iconName: "message-lock",
    defaultColor: "#3A76F0",
    category: "communication",
    keywords: ["signal", "chat", "secure", "messaging"],
  },
  messenger: {
    platform: "messenger",
    displayName: "Messenger",
    library: "MaterialCommunityIcons",
    iconName: "facebook-messenger",
    defaultColor: "#0084FF",
    category: "communication",
    keywords: ["messenger", "facebook", "chat", "meta"],
  },
  wechat: {
    platform: "wechat",
    displayName: "WeChat",
    library: "FontAwesome5",
    iconName: "weixin",
    defaultColor: "#09B83E",
    category: "communication",
    keywords: ["wechat", "weixin", "chat", "messaging"],
  },
  slack: {
    platform: "slack",
    displayName: "Slack",
    library: "FontAwesome5",
    iconName: "slack",
    defaultColor: "#4A154B",
    category: "communication",
    keywords: ["slack", "work", "team", "chat"],
  },
  zoom: {
    platform: "zoom",
    displayName: "Zoom",
    library: "MaterialCommunityIcons",
    iconName: "video",
    defaultColor: "#2D8CFF",
    category: "communication",
    keywords: ["zoom", "video", "meeting", "call"],
  },
  skype: {
    platform: "skype",
    displayName: "Skype",
    library: "FontAwesome5",
    iconName: "skype",
    defaultColor: "#00AFF0",
    category: "communication",
    keywords: ["skype", "video", "call", "microsoft"],
  },
  teams: {
    platform: "teams",
    displayName: "Microsoft Teams",
    library: "MaterialCommunityIcons",
    iconName: "microsoft-teams",
    defaultColor: "#6264A7",
    category: "communication",
    keywords: ["teams", "microsoft", "work", "meeting"],
  },
  gmail: {
    platform: "gmail",
    displayName: "Gmail",
    library: "MaterialCommunityIcons",
    iconName: "gmail",
    defaultColor: "#EA4335",
    category: "productivity",
    keywords: ["gmail", "email", "google", "mail"],
  },
  outlook: {
    platform: "outlook",
    displayName: "Outlook",
    library: "MaterialCommunityIcons",
    iconName: "microsoft-outlook",
    defaultColor: "#0078D4",
    category: "productivity",
    keywords: ["outlook", "email", "microsoft", "mail"],
  },
  yahoo: {
    platform: "yahoo",
    displayName: "Yahoo Mail",
    library: "FontAwesome5",
    iconName: "yahoo",
    defaultColor: "#6001D2",
    category: "productivity",
    keywords: ["yahoo", "email", "mail"],
  },
  protonmail: {
    platform: "protonmail",
    displayName: "ProtonMail",
    library: "MaterialCommunityIcons",
    iconName: "email-lock",
    defaultColor: "#8B89CC",
    category: "productivity",
    keywords: ["protonmail", "email", "secure", "mail"],
  },
  apple: {
    platform: "apple",
    displayName: "Apple",
    library: "FontAwesome5",
    iconName: "apple",
    defaultColor: "#000000",
    category: "other",
    keywords: ["apple", "icloud", "ios", "mac"],
  },
  gitlab: {
    platform: "gitlab",
    displayName: "GitLab",
    library: "FontAwesome5",
    iconName: "gitlab",
    defaultColor: "#FC6D26",
    category: "developer",
    keywords: ["gitlab", "git", "code", "developer"],
  },
  bitbucket: {
    platform: "bitbucket",
    displayName: "Bitbucket",
    library: "FontAwesome5",
    iconName: "bitbucket",
    defaultColor: "#0052CC",
    category: "developer",
    keywords: ["bitbucket", "git", "code", "developer"],
  },
  paypal: {
    platform: "paypal",
    displayName: "PayPal",
    library: "FontAwesome5",
    iconName: "paypal",
    defaultColor: "#00457C",
    category: "finance",
    keywords: ["paypal", "payment", "money"],
  },
  stripe: {
    platform: "stripe",
    displayName: "Stripe",
    library: "FontAwesome5",
    iconName: "stripe",
    defaultColor: "#635BFF",
    category: "finance",
    keywords: ["stripe", "payment", "money"],
  },
  venmo: {
    platform: "venmo",
    displayName: "Venmo",
    library: "MaterialCommunityIcons",
    iconName: "cash",
    defaultColor: "#3D95CE",
    category: "finance",
    keywords: ["venmo", "payment", "money"],
  },
  cashapp: {
    platform: "cashapp",
    displayName: "Cash App",
    library: "MaterialCommunityIcons",
    iconName: "currency-usd",
    defaultColor: "#00D632",
    category: "finance",
    keywords: ["cashapp", "cash", "payment", "square"],
  },
  revolut: {
    platform: "revolut",
    displayName: "Revolut",
    library: "MaterialCommunityIcons",
    iconName: "bank",
    defaultColor: "#0075EB",
    category: "finance",
    keywords: ["revolut", "banking", "finance"],
  },
  dropbox: {
    platform: "dropbox",
    displayName: "Dropbox",
    library: "FontAwesome5",
    iconName: "dropbox",
    defaultColor: "#0061FF",
    category: "storage",
    keywords: ["dropbox", "cloud", "storage", "files"],
  },
  googledrive: {
    platform: "googledrive",
    displayName: "Google Drive",
    library: "FontAwesome5",
    iconName: "google-drive",
    defaultColor: "#4285F4",
    category: "storage",
    keywords: ["google drive", "drive", "cloud", "storage", "google"],
  },
  onedrive: {
    platform: "onedrive",
    displayName: "OneDrive",
    library: "MaterialCommunityIcons",
    iconName: "microsoft-onedrive",
    defaultColor: "#0078D4",
    category: "storage",
    keywords: ["onedrive", "cloud", "storage", "microsoft"],
  },
  icloud: {
    platform: "icloud",
    displayName: "iCloud",
    library: "Ionicons",
    iconName: "cloud",
    defaultColor: "#3693F3",
    category: "storage",
    keywords: ["icloud", "apple", "cloud", "storage"],
  },
  box: {
    platform: "box",
    displayName: "Box",
    library: "MaterialCommunityIcons",
    iconName: "folder-multiple",
    defaultColor: "#0061D5",
    category: "storage",
    keywords: ["box", "cloud", "storage"],
  },
  notion: {
    platform: "notion",
    displayName: "Notion",
    library: "MaterialCommunityIcons",
    iconName: "notebook",
    defaultColor: "#000000",
    category: "productivity",
    keywords: ["notion", "notes", "productivity"],
  },
  trello: {
    platform: "trello",
    displayName: "Trello",
    library: "FontAwesome5",
    iconName: "trello",
    defaultColor: "#0052CC",
    category: "productivity",
    keywords: ["trello", "project", "kanban"],
  },
  asana: {
    platform: "asana",
    displayName: "Asana",
    library: "MaterialCommunityIcons",
    iconName: "check-circle",
    defaultColor: "#F06A6A",
    category: "productivity",
    keywords: ["asana", "project", "tasks"],
  },
  jira: {
    platform: "jira",
    displayName: "Jira",
    library: "MaterialCommunityIcons",
    iconName: "jira",
    defaultColor: "#0052CC",
    category: "productivity",
    keywords: ["jira", "project", "atlassian", "bugs"],
  },
  confluence: {
    platform: "confluence",
    displayName: "Confluence",
    library: "MaterialCommunityIcons",
    iconName: "file-document-multiple",
    defaultColor: "#172B4D",
    category: "productivity",
    keywords: ["confluence", "wiki", "atlassian"],
  },
  figma: {
    platform: "figma",
    displayName: "Figma",
    library: "FontAwesome5",
    iconName: "figma",
    defaultColor: "#F24E1E",
    category: "productivity",
    keywords: ["figma", "design", "ui", "ux"],
  },
  ebay: {
    platform: "ebay",
    displayName: "eBay",
    library: "FontAwesome5",
    iconName: "ebay",
    defaultColor: "#E53238",
    category: "shopping",
    keywords: ["ebay", "shopping", "auction"],
  },
  shopify: {
    platform: "shopify",
    displayName: "Shopify",
    library: "FontAwesome5",
    iconName: "shopify",
    defaultColor: "#7AB55C",
    category: "shopping",
    keywords: ["shopify", "ecommerce", "store"],
  },
  etsy: {
    platform: "etsy",
    displayName: "Etsy",
    library: "FontAwesome5",
    iconName: "etsy",
    defaultColor: "#F16521",
    category: "shopping",
    keywords: ["etsy", "shopping", "handmade"],
  },
  netflix: {
    platform: "netflix",
    displayName: "Netflix",
    library: "MaterialCommunityIcons",
    iconName: "netflix",
    defaultColor: "#E50914",
    category: "media",
    keywords: ["netflix", "streaming", "video", "movies"],
  },
  hulu: {
    platform: "hulu",
    displayName: "Hulu",
    library: "MaterialCommunityIcons",
    iconName: "play-circle",
    defaultColor: "#1CE783",
    category: "media",
    keywords: ["hulu", "streaming", "video"],
  },
  prime: {
    platform: "prime",
    displayName: "Prime Video",
    library: "MaterialCommunityIcons",
    iconName: "play-box",
    defaultColor: "#00A8E1",
    category: "media",
    keywords: ["prime", "amazon", "video", "streaming"],
  },
  disney: {
    platform: "disney",
    displayName: "Disney+",
    library: "MaterialCommunityIcons",
    iconName: "movie",
    defaultColor: "#113CCF",
    category: "media",
    keywords: ["disney", "streaming", "video"],
  },
  airbnb: {
    platform: "airbnb",
    displayName: "Airbnb",
    library: "FontAwesome5",
    iconName: "airbnb",
    defaultColor: "#FF5A5F",
    category: "travel",
    keywords: ["airbnb", "travel", "booking"],
  },
  uber: {
    platform: "uber",
    displayName: "Uber",
    library: "FontAwesome5",
    iconName: "uber",
    defaultColor: "#000000",
    category: "travel",
    keywords: ["uber", "ride", "travel"],
  },
  lyft: {
    platform: "lyft",
    displayName: "Lyft",
    library: "FontAwesome5",
    iconName: "lyft",
    defaultColor: "#FF00BF",
    category: "travel",
    keywords: ["lyft", "ride", "travel"],
  },
  booking: {
    platform: "booking",
    displayName: "Booking.com",
    library: "MaterialCommunityIcons",
    iconName: "bed",
    defaultColor: "#003580",
    category: "travel",
    keywords: ["booking", "hotel", "travel"],
  },
  stackoverflow: {
    platform: "stackoverflow",
    displayName: "Stack Overflow",
    library: "FontAwesome5",
    iconName: "stack-overflow",
    defaultColor: "#F58025",
    category: "developer",
    keywords: ["stackoverflow", "developer", "code", "questions"],
  },
  npm: {
    platform: "npm",
    displayName: "NPM",
    library: "FontAwesome5",
    iconName: "npm",
    defaultColor: "#CB3837",
    category: "developer",
    keywords: ["npm", "node", "package", "developer"],
  },
  docker: {
    platform: "docker",
    displayName: "Docker",
    library: "MaterialCommunityIcons",
    iconName: "docker",
    defaultColor: "#2496ED",
    category: "developer",
    keywords: ["docker", "container", "developer"],
  },
};

export const ICON_CATEGORIES = [
  { id: "social", label: "Social Media", icon: "people" },
  { id: "communication", label: "Communication", icon: "chatbubbles" },
  { id: "productivity", label: "Productivity", icon: "briefcase" },
  { id: "finance", label: "Finance & Trading", icon: "trending-up" },
  { id: "banking", label: "Banking", icon: "business" },
  { id: "crypto", label: "Cryptocurrency", icon: "logo-bitcoin" },
  { id: "identity", label: "Identity & Documents", icon: "card" },
  { id: "storage", label: "Cloud Storage", icon: "cloud" },
  { id: "media", label: "Media & Entertainment", icon: "play" },
  { id: "shopping", label: "Shopping", icon: "cart" },
  { id: "travel", label: "Travel", icon: "airplane" },
  { id: "gaming", label: "Gaming", icon: "game-controller" },
  { id: "education", label: "Education", icon: "school" },
  { id: "developer", label: "Developer Tools", icon: "code" },
  { id: "other", label: "Other", icon: "apps" },
] as const;

export const ICON_COLOR_PALETTE = [
  { name: "Red", value: "#F44336" },
  { name: "Pink", value: "#E91E63" },
  { name: "Purple", value: "#9C27B0" },
  { name: "Deep Purple", value: "#673AB7" },
  { name: "Indigo", value: "#3F51B5" },
  { name: "Blue", value: "#2196F3" },
  { name: "Light Blue", value: "#03A9F4" },
  { name: "Cyan", value: "#00BCD4" },
  { name: "Teal", value: "#009688" },
  { name: "Green", value: "#4CAF50" },
  { name: "Light Green", value: "#8BC34A" },
  { name: "Lime", value: "#CDDC39" },
  { name: "Yellow", value: "#FFEB3B" },
  { name: "Amber", value: "#FFC107" },
  { name: "Orange", value: "#FF9800" },
  { name: "Deep Orange", value: "#FF5722" },
  { name: "Brown", value: "#795548" },
  { name: "Grey", value: "#9E9E9E" },
  { name: "Blue Grey", value: "#607D8B" },
  { name: "Black", value: "#000000" },
];

export const getAllPlatformIcons = (): IconMapping[] => {
  return Object.values(PLATFORM_ICONS);
};

export const getIconsByCategory = (category: IconMapping["category"]): IconMapping[] => {
  return getAllPlatformIcons().filter((icon) => icon.category === category);
};

export const getPlatformCount = (): number => {
  return Object.keys(PLATFORM_ICONS).length;
};
